---
- hosts: 192.168.0.5
  tasks: 
    - name: s'assurer que httpd est actif
      service:  
        name: httpd
        state: started
      register: status
    - name: afficher le status  du service
      debug:
        msg: "{{status}}"
     
